id: rn2025
slug: rn2025
surveyId: state_of_react_native
context: state_of_react_native
topic: ReactNative
startedAt: December 5, 2025
endedAt: January 11, 2026
prettySlug: state-of-react-native
hashtag: StateOfReactNative
shareUrl: https://stateofreactnative.com
questionsUrl: https://survey.stateofreactnative.com/
faviconUrl: https://stateofreactnative.com/favicon.ico
socialImageUrl: https://survey.stateofreactnative.com/surveys/stateofreactnative2024.png
name: State of React Native
year: 2025
status: 3 # 1: preview, 2: open, 3: closed, 4: hidden
domain: stateofreactnative.com
tags:
  - rn
enableReadingList: true
enableChartSponsorships: false
enableSkip: true
colors:
  primary: rgb(71, 207, 237)
  secondary: '#8D4CA8'
  text: rgb(255, 246, 230)
  background: rgb(255, 255, 255)
  backgroundSecondary: rgb(48, 52, 53)
faq:
  - is_answering_every_question_mandatory
  - will_my_data_be_public
  - when_will_results_be_released
  - who_runs_the_survey
  - this_survey_looks_familiar
  - how_was_survey_design
