---
id: rn2023
slug: rn2023
surveyId: state_of_react_native
context: state_of_react_native
topic: JavaScript
createdAt: October 23, 2023
prettySlug: state-of-react-native
hashtag: StateOfReactNative
shareUrl: https://stateofreactnative.com
questionsUrl: https://survey.stateofreactnative.com/
# resultsUrl: https://2022.stateofjs.com/
faviconUrl: https://stateofreactnative.com/favicon.ico
socialImageUrl: https://survey.stateofreactnative.com/surveys/stateofreactnative2022-social.png
name: "State of React Native"
year: 2023
status: 3 # preview/open/closed/hidden - in order to change the status go to monorepo/surverform/src/surverys/stateofreactnative/rnXXXX
domain: stateofreactnative.com
tags: [rn]

colors:
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(255, 255, 255)
  backgroundSecondary: rgb(48, 52, 53)
